jobs : [
  # "dcgan",
  # "imagenet",
  #"vae",
  # "vision_transformer",
  #  "yolov8n",
  # "yolov8s",
  # "yolov8m",
  # "yolov8l",
  # "yolov8x",
  # "mnist",
  # "mnist_rnn",
  # "siamese_net",
  # "super_resolution",
  # "word_language",
  # "awd-lstm-lm",
  "gat",

]

node_and_gpu : [
  # ["gpu01", "gpu:gpu0:1"],
  # ["gpu01", "gpu:gpu1:1"],
  # ["gpu02", "gpu:gpu0:1"],
  ["gpu03", "gpu:gpu0:1"],
]

batch_size : {
    "dcgan":[32, 64, 128, 256, 512, 1024],
    "imagenet":[128, 256, 512, 1024, 2048, 4096],
    "vae":[128, 256, 512, 1024, 2048, 4096], 
    "vision_transformer":[4, 8, 12, 16], 
    "yolov8n":[4, 8, 16],
    "yolov8m":[2, 4, 8],
    "yolov8s":[4, 8, 16],
    "yolov8l":[2, 4, 8],
    "yolov8x":[2, 4, 8],
    "mnist":[32, 64, 128, 256, 512],
    "mnist_rnn":[32, 64, 128, 256, 512],
    "siamese_net":[32, 64, 128, 256, 512],
    "super_resolution":[32, 64, 128, 256, 512],
    "word_language" :[20,40,60,80,100],
    "awd-lstm-lm" :[40,80,120,160,200],
    "gat":[4,8,12,16,20]

}

train_file : {
  "dcgan": "models/dcgan/main.py",
  "imagenet":"models/imagenet/main.py",
  "vae" : "models/vae/main.py",
  "vision_transformer" : "models/vision_transformer/main.py",
  "yolov8n": "models/Yolov8/main.py yolov8n.pt",
  "yolov8s": "models/Yolov8/main.py yolov8s.pt",
  "yolov8m": "models/Yolov8/main.py yolov8m.pt",
  "yolov8l": "models/Yolov8/main.py yolov8l.pt",
  "yolov8x": "models/Yolov8/main.py yolov8x.pt",
  "mnist" : "models/mnist/main.py",
  "mnist_rnn" : "models/mnist_rnn/main.py",
  "siamese_net": "models/siamese_network/main.py",
  "super_resolution": "models/super_resolution/main.py",
  "word_language": "models/word_language_model/main.py",
  "awd-lstm-lm": "models/awd-lstm-lm/main.py",
  "gat": "models/gat/main.py",
}


# possible_jobs : {

# }
