#######################################
# yaml file for log_start.py
# control node_and_gpu.
#######################################
# possible node and gpu
node_and_gpu : [
  ["worker1", "gpu01-gpu0"],
  ["worker2", "gpu01-gpu0"],
  ["worker3", "gpu01-gpu0"],
  # ["gpu03", "gpu02-gpu0"],
]

