#######################################
# yaml file for log_start.py
# control node_and_gpu.
#######################################
# possible node and gpu
node_and_gpu : [
  ["worker01", "gpu01-gpu0"],
  ["worker01", "gpu01-gpu1"],
  ["worker02", "gpu01-gpu1"],
  ["worker03", "gpu01-gpu1"],
  ["worker04", "gpu01-gpu0"],
  ["worker05", "gpu01-gpu1"],
  ["worker06", "gpu01-gpu0"],
]
