#######################################
# yaml file for log_start.py
# control node_and_gpu.
#######################################
# possible node and gpu
node_and_gpu : [
  # ["worker01", "gpu01-gpu0", 'gpu01'],
  # ["worker01", "gpu01-gpu1", 'gpu02'],
  # ["worker02", "gpu01-gpu1", 'gpu03'],
  # ["worker03", "gpu01-gpu1", 'gpu04'],
  ["worker04", "gpu01-gpu0", 'gpu05'],
  ["worker05", "gpu01-gpu1", 'gpu06'],
  ["worker06", "gpu01-gpu0", 'gpu07'],
]
