#######################################
# yaml file for log_start.py
# control node_and_gpu.
#######################################
# possible node and gpu
node_and_gpu : [
  ["worker01", "8G", 'gpu01'], # RTX 3070ti
  ["worker01", "24G", 'gpu02'], # RTX 3090
  ["worker02", "24G", 'gpu03'], # RTX 4090
  ["worker03", "16G", 'gpu04'], # RTX 4080
  ["worker04", "8G", 'gpu05'], # RTX 4060
  ["worker05", "12G", 'gpu06'], # RTX 4070
  ["worker06", "8G", 'gpu07'], # RTX 4060
]
