#######################################
# yaml file for log_start.py
# control node_and_gpu.
#######################################
# possible node and gpu
node_and_gpu : [
  ["worker01", "memory8", 'gpu01'], # RTX 3070ti
  ["worker01", "memory24", 'gpu02'], # RTX 3090
  ["worker02", "memory24", 'gpu03'], # RTX 4090
  ["worker03", "memory16", 'gpu04'], # RTX 4080
  ["worker04", "memory8", 'gpu05'], # RTX 4060
  ["worker05", "memory12", 'gpu06'], # RTX 4070
  ["worker06", "memory8", 'gpu07'], # RTX 4060
]
